# NumPy Notes

- NumPy is a python library which stands for "Numerical Python"
- is used for **working with arrays**.

In [2]:
# %pip install numpy
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


- has functions for working in domain of linear algebra, fourier transform, matrices etc.
- python **lists** are slow, NumPy array object (ndarray) is faster and provides many functions for working with arrays.

> NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

In [16]:
print(np.__version__)

2.0.0


To create an ndarray, we can pass a list, tuple or any array-like object into the `array()` method, and it will be converted into an ndarray:

In [21]:
a = np.array([1, 2, 3, 4, 5])    # list
b = np.array((1, 2, 3))  # tuple
# set (not recommended, order can change)
c = np.array({1, 2, 3, 77, 8, 9})  
print(a, type(a))
print(b, type(b))
print(c, type(c))

[1 2 3 4 5] <class 'numpy.ndarray'>
[1 2 3] <class 'numpy.ndarray'>
{1, 2, 3, 8, 9, 77} <class 'numpy.ndarray'>


## Dimensions in Arrays

- A dimension in arrays is one level of array depth (nested arrays).
- nested arrays are arrays that have arrays as their elements.

### 0-D Arrays (Scalars)

- It's an array with no dimensions, containing a single element

In [22]:
arr = np.array(42)
print(arr, type(arr))

42 <class 'numpy.ndarray'>


### 1-D Arrays

- array having 0-D arrays as its elements.

In [23]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


### 2-D Arrays

- array having 1-D arrays as its elements.
- most common type of array, often used to represent matrix or 2nd order tensor.
    - **tensor** is a generalized form of matrices and vectors that can handle higher dimensions than just 2D or 1D structures.

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, type(arr))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


### 3-D Arrays

- array having 2-D arrays as its elements.
- often used to represent a 3rd order tensor.
    - **Example**: create a 3-D array with two 2-D arrays, both containing two arrays with the values 1, 2, 3 and 4, 5, 6:

In [30]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr, type(arr))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] <class 'numpy.ndarray'>


## How to check the number of dimensions?

- `ndim` attribute

In [31]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays

- using `ndmin` argument while creating an array.

In [32]:
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions : 5


# NumPy Array Indexing

In [34]:
arr = np.array([1, 2, 3, 4])
print(arr[0])   # 1
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('2nd element on 1st dim: ', arr[0, 1])    # 2
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2]) # 6

1
2nd element on 1st dim:  2
6


- `arr[0, 1, 2]` prints the value $6$ :
    - first number represents first dimension, which contains two arrays `[[1, 2, 3], [4, 5, 6]]` and `[[7, 8, 9], [10, 11, 12]]`. Since we selected $0$, we are left with the first array `[[1, 2, 3], [4, 5, 6]]`
    - second number represents the second dimension, which also contains two arrays `[1, 2, 3]` and `[4, 5, 6]`. Since we selected $1$, we are left with the second array `[4, 5, 6]`
    - third number represents the third dimension, which contains three values, `4`, `5` and `6`. Since we selected $2$, we end up with the third value: $6$

### Negative Indexing

In [35]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('Last element from 2nd dim: ', arr[1, -1])    # 10

Last element from 2nd dim:  10


# NumPy Array Slicing

- **slicing** allows extracting subsequence from a sequence.
- `[start:end:step]` where `start` is inclusive, `end` is exclusive.
- default values are `start=0`, `end=len(array)`, `step=1`

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])     # [2 3 4 5]
print(arr[4:])      # [5 6 7]
print(arr[-3:-1])   # [5 6]
print(arr[-2:-7:-2])    # [6 4 2]

[2 3 4 5]
[5 6 7]
[5 6]
[6 4 2]


# NumPy Data Types

### Data Types in Python

- `str`, `int`, `float`, `complex`, `bool` etc
- `type()` function to know the data type of any object.

## NumPy Data Types

- `i` - integer
- `b` - boolean
- `u` - unsigned integer
- `f` - float
- `c` - complex float
- `m` - timedelta
- `M` - datetime
- `O` - object
- `S` - string
- `U` - unicode string
- `V` - fixed chunk of memory for other type ( void )

> `dtype` attribute is used to check the data type of an array's elements.

In [28]:
a = np.array([1, 2, 3, 4])
b = np.array(["alok", "shandilya", 1])  # here, 1 is converted to string
print(a.dtype)
print(b.dtype)
print(type(b[2]))
print(b[2] + "1")

int64
<U21
<class 'numpy.str_'>
11


### Creating Arrays with a Defined Data Type

- optional `dtype` argument

In [30]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


- for `i`, `u`, `f`, `S` and `U` we can define size as well.
- `astype()` method to convert data type of an existing array.

In [50]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4], dtype='i4')  # 4 bytes integer (32 bits)
print(a, type(a))
print(a.dtype)
print(b, type(b))
print(b.dtype)

arr = np.array([1, 2, 3], dtype="f")
print(arr)

arr = np.array([1.1, 2.1, 3.9])
newarr = arr.astype("i")    # astype("i") converts to 32-bit integer
print(newarr)
print(newarr.dtype)

newarr = arr.astype("int64")
print(newarr)
print(newarr.dtype)

[1 2 3 4] <class 'numpy.ndarray'>
int64
[1 2 3 4] <class 'numpy.ndarray'>
int32
[1. 2. 3.]
[1 2 3]
int32
[1 2 3]
int64


In [43]:
# will raise ValueError as string cannot be converted to int
arr = np.array(["alok", "shandilya", 7], dtype="i")

ValueError: invalid literal for int() with base 10: 'alok'

In [52]:
arr = np.array([1, 0, 3, 7.7])
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True  True]
bool


# NumPy array `Copy` vs `View`

- `copy()` when need an independent array.
    - creates a deep copy
- `view()` when need a new array that shares data with the original array for memory efficiency.
    - creates a shallow copy

In [2]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [3]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


`base` attribute in NumPy is used to check if an array is a `view` of another array. If an array is a `view`, the `base` attribute points to the original array. If the array owns its own data (i.e., it is not a `view` but a `copy`), the `base` attribute is `None`

In [2]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# NumPy array shape

- `shape` attribute returns a tuple with each index having the number of corresponding elements.

In [8]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
print(type(arr.shape))

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(arr.shape)  # (1, 1, 1, 1, 4)
# means 1 element in 1 dimension, 1 element in 2nd dimension, 1 element in 3rd dimension, 1 element in 4th dimension and 4 elements in 5th dimension

(2, 4)
<class 'tuple'>
[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


# Numpy Array Reshaping

- `reshape()` method to change the shape of an array.

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

print()

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


- we can reshape into any shape as long as the total number of elements remains the same.

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

The `reshape()` function in NumPy returns a **view** (shallow copy) of the original array whenever possible. This means that the data is not actually copied, and both the original and the reshaped arrays share the same underlying data. However, if it is not possible to return a view, `reshape()` will return a new array (deep copy).

- the `reshape()` method returns the original array, so it's a `view`
- > **Note**: we can not pass $-1$ to more than one dimension.

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = arr[1:5]
test = newarr.reshape(2, 2)
print(test)
print(test.base)

[[2 3]
 [4 5]]
[1 2 3 4 5 6]


### Flattening the arrays

- `reshape(-1)` to flatten the array (convert it into a 1D array).
- > **Note**: there are a lot of ways to flatten an array, but `reshape(-1)` is the most common and easiest way to do it. `flatten()`, `ravel()` are other methods. Also, for rearranging the elements `rot90()`, `flip()`, `fliplr()`, `flipud()` etc are used.

In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.reshape(-1))

[1 2 3 4 5 6]
