# NumPy Notes

- NumPy is a python library which stands for "Numerical Python"
- is used for **working with arrays**.

In [2]:
# %pip install numpy
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


- has functions for working in domain of linear algebra, fourier transform, matrices etc.
- python **lists** are slow, NumPy array object (ndarray) is faster and provides many functions for working with arrays.

> NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

In [16]:
print(np.__version__)

2.0.0


To create an ndarray, we can pass a list, tuple or any array-like object into the `array()` method, and it will be converted into an ndarray:

In [21]:
a = np.array([1, 2, 3, 4, 5])    # list
b = np.array((1, 2, 3))  # tuple
# set (not recommended, order can change)
c = np.array({1, 2, 3, 77, 8, 9})  
print(a, type(a))
print(b, type(b))
print(c, type(c))

[1 2 3 4 5] <class 'numpy.ndarray'>
[1 2 3] <class 'numpy.ndarray'>
{1, 2, 3, 8, 9, 77} <class 'numpy.ndarray'>


## Dimensions in Arrays

- A dimension in arrays is one level of array depth (nested arrays).
- nested arrays are arrays that have arrays as their elements.

### 0-D Arrays (Scalars)

- It's an array with no dimensions, containing a single element

In [22]:
arr = np.array(42)
print(arr, type(arr))

42 <class 'numpy.ndarray'>


### 1-D Arrays

- array having 0-D arrays as its elements.

In [23]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


### 2-D Arrays

- array having 1-D arrays as its elements.
- most common type of array, often used to represent matrix or 2nd order tensor.
    - **tensor** is a generalized form of matrices and vectors that can handle higher dimensions than just 2D or 1D structures.

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, type(arr))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


### 3-D Arrays

- array having 2-D arrays as its elements.
- often used to represent a 3rd order tensor.
    - **Example**: create a 3-D array with two 2-D arrays, both containing two arrays with the values 1, 2, 3 and 4, 5, 6:

In [30]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr, type(arr))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] <class 'numpy.ndarray'>


## How to check the number of dimensions?

- `ndim` attribute

In [31]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays

- using `ndmin` argument while creating an array.

In [32]:
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions : 5


# NumPy Array Indexing

In [34]:
arr = np.array([1, 2, 3, 4])
print(arr[0])   # 1
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('2nd element on 1st dim: ', arr[0, 1])    # 2
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2]) # 6

1
2nd element on 1st dim:  2
6


- `arr[0, 1, 2]` prints the value $6$ :
    - first number represents first dimension, which contains two arrays `[[1, 2, 3], [4, 5, 6]]` and `[[7, 8, 9], [10, 11, 12]]`. Since we selected $0$, we are left with the first array `[[1, 2, 3], [4, 5, 6]]`
    - second number represents the second dimension, which also contains two arrays `[1, 2, 3]` and `[4, 5, 6]`. Since we selected $1$, we are left with the second array `[4, 5, 6]`
    - third number represents the third dimension, which contains three values, `4`, `5` and `6`. Since we selected $2$, we end up with the third value: $6$

### Negative Indexing

In [35]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('Last element from 2nd dim: ', arr[1, -1])    # 10

Last element from 2nd dim:  10


# NumPy Array Slicing

- **slicing** allows extracting subsequence from a sequence.
- `[start:end:step]` where `start` is inclusive, `end` is exclusive.
- default values are `start=0`, `end=len(array)`, `step=1`

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])     # [2 3 4 5]
print(arr[4:])      # [5 6 7]
print(arr[-3:-1])   # [5 6]
print(arr[-2:-7:-2])    # [6 4 2]

[2 3 4 5]
[5 6 7]
[5 6]
[6 4 2]


# NumPy Data Types

### Data Types in Python

- `str`, `int`, `float`, `complex`, `bool` etc
- `type()` function to know the data type of any object.

## NumPy Data Types

- `i` - integer
- `b` - boolean
- `u` - unsigned integer
- `f` - float
- `c` - complex float
- `m` - timedelta
- `M` - datetime
- `O` - object
- `S` - string
- `U` - unicode string
- `V` - fixed chunk of memory for other type ( void )

> `dtype` attribute is used to check the data type of an array's elements.

In [28]:
a = np.array([1, 2, 3, 4])
b = np.array(["alok", "shandilya", 1])  # here, 1 is converted to string
print(a.dtype)
print(b.dtype)
print(type(b[2]))
print(b[2] + "1")

int64
<U21
<class 'numpy.str_'>
11


### Creating Arrays with a Defined Data Type

- optional `dtype` argument

In [30]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


- for `i`, `u`, `f`, `S` and `U` we can define size as well.
- `astype()` method to convert data type of an existing array.

In [50]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4], dtype='i4')  # 4 bytes integer (32 bits)
print(a, type(a))
print(a.dtype)
print(b, type(b))
print(b.dtype)

arr = np.array([1, 2, 3], dtype="f")
print(arr)

arr = np.array([1.1, 2.1, 3.9])
newarr = arr.astype("i")    # astype("i") converts to 32-bit integer
print(newarr)
print(newarr.dtype)

newarr = arr.astype("int64")
print(newarr)
print(newarr.dtype)

[1 2 3 4] <class 'numpy.ndarray'>
int64
[1 2 3 4] <class 'numpy.ndarray'>
int32
[1. 2. 3.]
[1 2 3]
int32
[1 2 3]
int64


In [43]:
# will raise ValueError as string cannot be converted to int
arr = np.array(["alok", "shandilya", 7], dtype="i")

ValueError: invalid literal for int() with base 10: 'alok'

In [52]:
arr = np.array([1, 0, 3, 7.7])
newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True  True]
bool


# NumPy array `Copy` vs `View`

- [link](https://www.w3schools.com/python/numpy/numpy_copy_vs_view.asp)